### ISSUE TITLE
About Franca_ara converter's version.

### ISSUE THREAD

**Issue by HaesungDaddy** [COVESA/franca_ara_tools#150]
Hello there. 
I have simple question related with executable version information.

I downloaded the source version 0.9 and build 'faracon-windows-x86_64.exe' file successfully.
I Executed the converter in command prompt and enter '-version'
But version information 0.7.0 displayed different from my expectation(0.9.x)
![image](https://user-images.githubusercontent.com/59278228/71509154-a7fcf100-28cd-11ea-8156-67b2bbd1e3b0.png)

So, I don't know whether my EXE is latest version or not.
Could you give some advices for this?

Thank you.

**Comment by TorstenGoerg** [comment]
Hi HaesungDaddy,

the version number and the build id that are shown when calling faracon with the command line option "-version" just had not been updated properly. The version of the tool that you downloaded ws indeed 0.9.

Please notice that meanwhile version 1.0 of faracon is available that completely covers all features od Franca IDL ([https://github.com/GENIVI/franca_ara_tools/releases/tag/Release_1.0](https://github.com/GENIVI/franca_ara_tools/releases/tag/Release_1.0)).

**Comment by HaesungDaddy** [comment]
Hi TorstenGoerg.
Thank you for your answer.
So, I am using 0.9 version now.

I have 1more question about Franca_ara converter.
I have 1 pair franca files (.fidl and .fdepl extention, file name is same).
Using F2A works well, but contents of .fdepl are not applied to arxml.
I guess the converter doesn't deal with .fdepl files.

I wonder that F2A funtion incluedes network property(e.g. ip address, mac address, port number) in .fdepl. If not, is there any plan for supporting .fdepl?

**Comment by kbirken** [comment]
The latest changes done during the past months added some support for fdepl deployment for SOME/IP. However, the instance-related configuration parameters are still not supported. This is not on the roadmap right now because of missing funding.
